#!/usr/bin/python
import sys

def main(argv=None):
	temp0 = 0.797395315875 * 58.5782202346
	if temp0 != 0: temp1 = temp0 / temp0
	else: temp1 = temp0
	if temp1 != 0: temp0 = temp1 % temp1
	else: temp0 = temp1
	if temp1 != 0: temp2 = temp0 / temp1
	else: temp2 = temp0
	temp3 = temp0 + temp2
	if temp2 != 0: temp1 = temp1 % temp2
	else: temp1 = temp1
	if temp2 != 0: temp4 = temp1 / temp2
	else: temp4 = temp1
	temp3 = temp4 * temp0
	temp3 = temp1 + temp4
	temp3 = 9.07688356746 - 7.97401465711
	temp3 = max(temp2, temp3)
	temp1 = temp4 * temp2
	temp2 = temp1 - 67.3014450455
	temp1 = temp2 - temp1
	if temp1 != 0: temp2 = 26.5043346924 / temp1
	else: temp2 = 26.5043346924
	temp0 = max(temp1, temp4)
	temp5 = temp2 - temp1
	if temp2 != 0: temp1 = temp0 / temp2
	else: temp1 = temp0
	temp6 = temp1 + 25.8142455302
	print temp6

if __name__ == '__main__':
	sys.exit(main())
